-- Documents the pre-existing mood-tracking schema that app/page.tsx already
-- queries against (mood_checkins, mood_tags, mood_checkin_tags). These
-- tables predate migration files in this repo; this migration exists so the
-- schema is captured as code and database.types.ts has something to match.
-- If these tables already exist in your database, this is a no-op.

create table if not exists public.mood_checkins (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  stress_level int not null check (stress_level between 0 and 10),
  mode text not null check (mode in ('Quick', 'Daily', 'Detailed')),
  notes text
);

create table if not exists public.mood_tags (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  label text not null
);

create table if not exists public.mood_checkin_tags (
  checkin_id uuid not null references public.mood_checkins(id) on delete cascade,
  tag_id bigint not null references public.mood_tags(id) on delete cascade,
  primary key (checkin_id, tag_id)
);

alter table public.mood_checkins enable row level security;
alter table public.mood_tags enable row level security;
alter table public.mood_checkin_tags enable row level security;

drop policy if exists "mood_checkins: owner full access" on public.mood_checkins;
create policy "mood_checkins: owner full access"
  on public.mood_checkins for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "mood_tags: readable by all signed-in users" on public.mood_tags;
create policy "mood_tags: readable by all signed-in users"
  on public.mood_tags for select
  using (auth.role() = 'authenticated');

drop policy if exists "mood_tags: insertable by all signed-in users" on public.mood_tags;
create policy "mood_tags: insertable by all signed-in users"
  on public.mood_tags for insert
  with check (auth.role() = 'authenticated');

drop policy if exists "mood_checkin_tags: owner full access" on public.mood_checkin_tags;
create policy "mood_checkin_tags: owner full access"
  on public.mood_checkin_tags for all
  using (
    exists (
      select 1 from public.mood_checkins c
      where c.id = checkin_id and c.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.mood_checkins c
      where c.id = checkin_id and c.user_id = auth.uid()
    )
  );
