import type { Exercise } from "./types";

// A body-inclusive, full-body exercise library. Every movement pattern has a
// foundation-tier, no-equipment option so the app works regardless of a
// person's weight, height, fitness level, or access to a gym. Harder/equipment
// variants exist as substitutions once someone is ready for them.
export const EXERCISE_LIBRARY: Exercise[] = [
  // ---- Mobility (warm-up / cooldown, safe for everyone) -------------------
  {
    id: "arm_circles",
    name: "Arm Circles",
    pattern: "mobility",
    muscleGroups: ["shoulders"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: [],
    cues: ["Small circles first, then widen.", "Keep shoulders relaxed away from ears."],
    defaultSets: 1,
    defaultReps: 20,
    caloriesPerMinute: 3,
  },
  {
    id: "cat_cow",
    name: "Cat-Cow Stretch",
    pattern: "mobility",
    muscleGroups: ["back", "core"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: [],
    cues: ["Move with your breath.", "Arch on inhale, round on exhale."],
    defaultSets: 1,
    defaultReps: 10,
    caloriesPerMinute: 3,
  },
  {
    id: "leg_swings",
    name: "Leg Swings",
    pattern: "mobility",
    muscleGroups: ["hamstrings", "glutes"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: ["hip"],
    cues: ["Hold something for balance.", "Swing from the hip, not the knee."],
    defaultSets: 1,
    defaultReps: 12,
    caloriesPerMinute: 3,
  },
  {
    id: "hip_circles",
    name: "Hip Circles",
    pattern: "mobility",
    muscleGroups: ["glutes", "core"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: ["hip"],
    cues: ["Hands on hips, trace a big circle.", "Keep knees soft."],
    defaultSets: 1,
    defaultReps: 10,
    caloriesPerMinute: 3,
  },
  {
    id: "childs_pose",
    name: "Child's Pose",
    pattern: "mobility",
    muscleGroups: ["back"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: ["knee"],
    cues: ["Sit hips back toward heels.", "Let your back round and relax."],
    defaultSets: 1,
    defaultReps: 30,
    isTimeBased: true,
    caloriesPerMinute: 2,
  },
  {
    id: "standing_quad_stretch",
    name: "Standing Quad Stretch",
    pattern: "mobility",
    muscleGroups: ["quads"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: ["knee"],
    cues: ["Hold a wall for balance.", "Pull heel gently toward glutes."],
    defaultSets: 1,
    defaultReps: 20,
    isTimeBased: true,
    caloriesPerMinute: 2,
  },
  {
    id: "shoulder_stretch",
    name: "Cross-Body Shoulder Stretch",
    pattern: "mobility",
    muscleGroups: ["shoulders"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: ["shoulder"],
    cues: ["Pull elbow gently across chest.", "Keep shoulder down, not hunched."],
    defaultSets: 1,
    defaultReps: 20,
    isTimeBased: true,
    caloriesPerMinute: 2,
  },
  {
    id: "seated_forward_fold",
    name: "Seated Forward Fold",
    pattern: "mobility",
    muscleGroups: ["hamstrings", "back"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: ["back"],
    cues: ["Hinge from the hips, not the waist.", "Only go as far as feels good."],
    defaultSets: 1,
    defaultReps: 30,
    isTimeBased: true,
    caloriesPerMinute: 2,
  },

  // ---- Push -----------------------------------------------------------------
  {
    id: "incline_pushup",
    name: "Incline Push-Up",
    pattern: "push",
    muscleGroups: ["chest", "shoulders", "triceps"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: ["wrist", "shoulder"],
    cues: ["Hands on a counter or step.", "Body in a straight line, core braced."],
    defaultSets: 2,
    defaultReps: 8,
    caloriesPerMinute: 5,
    harderId: "knee_pushup",
  },
  {
    id: "knee_pushup",
    name: "Kneeling Push-Up",
    pattern: "push",
    muscleGroups: ["chest", "shoulders", "triceps"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: ["wrist", "shoulder", "knee"],
    cues: ["Knees, hips, shoulders in one line.", "Lower chest toward the floor."],
    defaultSets: 2,
    defaultReps: 8,
    caloriesPerMinute: 5,
    easierId: "incline_pushup",
    harderId: "pushup",
  },
  {
    id: "pushup",
    name: "Push-Up",
    pattern: "push",
    muscleGroups: ["chest", "shoulders", "triceps"],
    equipment: ["none"],
    tier: "building",
    impact: "low",
    cautionJoints: ["wrist", "shoulder"],
    cues: ["Elbows ~45 degrees from body.", "Full lockout at the top."],
    defaultSets: 3,
    defaultReps: 10,
    caloriesPerMinute: 6,
    easierId: "knee_pushup",
    harderId: "decline_pushup",
  },
  {
    id: "decline_pushup",
    name: "Decline Push-Up",
    pattern: "push",
    muscleGroups: ["chest", "shoulders", "triceps"],
    equipment: ["bench", "none"],
    tier: "progressing",
    impact: "low",
    cautionJoints: ["wrist", "shoulder"],
    cues: ["Feet elevated on a step or bench.", "Keep hips from sagging."],
    defaultSets: 3,
    defaultReps: 10,
    caloriesPerMinute: 6,
    easierId: "pushup",
  },
  {
    id: "pike_pushup",
    name: "Pike Push-Up",
    pattern: "push",
    muscleGroups: ["shoulders", "triceps"],
    equipment: ["none"],
    tier: "progressing",
    impact: "low",
    cautionJoints: ["wrist", "shoulder"],
    cues: ["Hips high, forming an inverted V.", "Lower crown of head toward floor."],
    defaultSets: 3,
    defaultReps: 8,
    caloriesPerMinute: 6,
  },
  {
    id: "dumbbell_shoulder_press",
    name: "Dumbbell Shoulder Press",
    pattern: "push",
    muscleGroups: ["shoulders", "triceps"],
    equipment: ["dumbbells", "full_gym"],
    tier: "building",
    impact: "low",
    cautionJoints: ["shoulder"],
    cues: ["Press straight overhead.", "Avoid arching your lower back."],
    defaultSets: 3,
    defaultReps: 10,
    caloriesPerMinute: 6,
  },

  // ---- Pull -------------------------------------------------------------
  {
    id: "band_pull_apart",
    name: "Band Pull-Apart",
    pattern: "pull",
    muscleGroups: ["back", "shoulders"],
    equipment: ["resistance_bands"],
    tier: "foundation",
    impact: "low",
    cautionJoints: ["shoulder"],
    cues: ["Arms straight, pull band to chest.", "Squeeze shoulder blades together."],
    defaultSets: 2,
    defaultReps: 12,
    caloriesPerMinute: 4,
    harderId: "doorway_row",
  },
  {
    id: "doorway_row",
    name: "Doorway / Table Row",
    pattern: "pull",
    muscleGroups: ["back", "biceps"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: ["shoulder"],
    cues: ["Hold a sturdy edge, lean back.", "Pull chest toward your hands."],
    defaultSets: 2,
    defaultReps: 10,
    caloriesPerMinute: 4,
    easierId: "band_pull_apart",
    harderId: "inverted_row",
  },
  {
    id: "inverted_row",
    name: "Inverted Row",
    pattern: "pull",
    muscleGroups: ["back", "biceps"],
    equipment: ["pull_up_bar", "full_gym"],
    tier: "building",
    impact: "low",
    cautionJoints: ["shoulder"],
    cues: ["Body straight under a low bar.", "Pull chest to the bar."],
    defaultSets: 3,
    defaultReps: 10,
    caloriesPerMinute: 5,
    easierId: "doorway_row",
    harderId: "pullup_negative",
  },
  {
    id: "pullup_negative",
    name: "Negative Pull-Up",
    pattern: "pull",
    muscleGroups: ["back", "biceps"],
    equipment: ["pull_up_bar"],
    tier: "progressing",
    impact: "low",
    cautionJoints: ["shoulder"],
    cues: ["Jump or step to the top position.", "Lower yourself as slowly as possible."],
    defaultSets: 3,
    defaultReps: 5,
    caloriesPerMinute: 6,
    easierId: "inverted_row",
    harderId: "pullup",
  },
  {
    id: "pullup",
    name: "Pull-Up",
    pattern: "pull",
    muscleGroups: ["back", "biceps"],
    equipment: ["pull_up_bar"],
    tier: "advanced",
    impact: "low",
    cautionJoints: ["shoulder"],
    cues: ["Full hang to chin over the bar.", "Control the descent."],
    defaultSets: 4,
    defaultReps: 6,
    caloriesPerMinute: 7,
    easierId: "pullup_negative",
  },
  {
    id: "dumbbell_bent_row",
    name: "Dumbbell Bent-Over Row",
    pattern: "pull",
    muscleGroups: ["back", "biceps"],
    equipment: ["dumbbells", "full_gym"],
    tier: "building",
    impact: "low",
    cautionJoints: ["back", "shoulder"],
    cues: ["Hinge forward, flat back.", "Row elbows toward your hips."],
    defaultSets: 3,
    defaultReps: 10,
    caloriesPerMinute: 5,
  },

  // ---- Squat --------------------------------------------------------------
  {
    id: "bodyweight_squat",
    name: "Bodyweight Squat",
    pattern: "squat",
    muscleGroups: ["quads", "glutes"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: ["knee"],
    cues: ["Feet shoulder-width, chest tall.", "Sit back like into a chair."],
    defaultSets: 2,
    defaultReps: 10,
    caloriesPerMinute: 5,
    harderId: "goblet_squat",
  },
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    pattern: "squat",
    muscleGroups: ["quads", "glutes"],
    equipment: ["dumbbells", "kettlebell", "full_gym"],
    tier: "building",
    impact: "low",
    cautionJoints: ["knee"],
    cues: ["Hold weight close to chest.", "Elbows brush inside of knees at bottom."],
    defaultSets: 3,
    defaultReps: 10,
    caloriesPerMinute: 6,
    easierId: "bodyweight_squat",
    harderId: "split_squat",
  },
  {
    id: "split_squat",
    name: "Split Squat",
    pattern: "squat",
    muscleGroups: ["quads", "glutes"],
    equipment: ["none"],
    tier: "building",
    impact: "low",
    cautionJoints: ["knee"],
    cues: ["Long staggered stance.", "Drop back knee straight down."],
    defaultSets: 3,
    defaultReps: 8,
    caloriesPerMinute: 6,
    easierId: "goblet_squat",
    harderId: "bulgarian_split_squat",
  },
  {
    id: "bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    pattern: "squat",
    muscleGroups: ["quads", "glutes"],
    equipment: ["bench", "none"],
    tier: "progressing",
    impact: "low",
    cautionJoints: ["knee"],
    cues: ["Rear foot elevated behind you.", "Front shin stays mostly vertical."],
    defaultSets: 3,
    defaultReps: 8,
    caloriesPerMinute: 7,
    easierId: "split_squat",
    harderId: "jump_squat",
  },
  {
    id: "jump_squat",
    name: "Jump Squat",
    pattern: "squat",
    muscleGroups: ["quads", "glutes", "calves"],
    equipment: ["none"],
    tier: "advanced",
    impact: "high",
    cautionJoints: ["knee", "ankle"],
    cues: ["Squat down, explode straight up.", "Land soft with bent knees."],
    defaultSets: 4,
    defaultReps: 10,
    caloriesPerMinute: 10,
    easierId: "bulgarian_split_squat",
  },

  // ---- Hinge --------------------------------------------------------------
  {
    id: "glute_bridge",
    name: "Glute Bridge",
    pattern: "hinge",
    muscleGroups: ["glutes", "hamstrings"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: ["back"],
    cues: ["Feet hip-width, close to glutes.", "Squeeze glutes at the top."],
    defaultSets: 2,
    defaultReps: 12,
    caloriesPerMinute: 4,
    harderId: "romanian_deadlift",
  },
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift",
    pattern: "hinge",
    muscleGroups: ["hamstrings", "glutes", "back"],
    equipment: ["none", "dumbbells", "full_gym"],
    tier: "building",
    impact: "low",
    cautionJoints: ["back"],
    cues: ["Push hips back, soft knees.", "Keep the weight close to your legs."],
    defaultSets: 3,
    defaultReps: 10,
    caloriesPerMinute: 5,
    easierId: "glute_bridge",
    harderId: "single_leg_deadlift",
  },
  {
    id: "single_leg_glute_bridge",
    name: "Single-Leg Glute Bridge",
    pattern: "hinge",
    muscleGroups: ["glutes", "hamstrings"],
    equipment: ["none"],
    tier: "progressing",
    impact: "low",
    cautionJoints: ["back"],
    cues: ["One foot planted, other leg extended.", "Keep hips level throughout."],
    defaultSets: 3,
    defaultReps: 8,
    caloriesPerMinute: 5,
    easierId: "glute_bridge",
  },
  {
    id: "single_leg_deadlift",
    name: "Single-Leg Deadlift",
    pattern: "hinge",
    muscleGroups: ["hamstrings", "glutes", "core"],
    equipment: ["none", "dumbbells"],
    tier: "advanced",
    impact: "low",
    cautionJoints: ["back", "ankle"],
    cues: ["Hinge on one leg, other reaches back.", "Keep hips square to the floor."],
    defaultSets: 3,
    defaultReps: 8,
    caloriesPerMinute: 6,
    easierId: "romanian_deadlift",
  },

  // ---- Core -----------------------------------------------------------------
  {
    id: "dead_bug",
    name: "Dead Bug",
    pattern: "core_stability",
    muscleGroups: ["core"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: ["back"],
    cues: ["Press lower back into the floor.", "Move opposite arm and leg slowly."],
    defaultSets: 2,
    defaultReps: 10,
    caloriesPerMinute: 3,
    harderId: "plank",
  },
  {
    id: "plank",
    name: "Plank",
    pattern: "core_stability",
    muscleGroups: ["core"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: ["back", "shoulder"],
    cues: ["Straight line from head to heels.", "Squeeze glutes, don't let hips sag."],
    defaultSets: 2,
    defaultReps: 20,
    isTimeBased: true,
    caloriesPerMinute: 4,
    easierId: "dead_bug",
    harderId: "side_plank",
  },
  {
    id: "side_plank",
    name: "Side Plank",
    pattern: "core_stability",
    muscleGroups: ["core"],
    equipment: ["none"],
    tier: "building",
    impact: "low",
    cautionJoints: ["shoulder"],
    cues: ["Stack feet or stagger for balance.", "Lift hips so body forms a straight line."],
    defaultSets: 2,
    defaultReps: 15,
    isTimeBased: true,
    caloriesPerMinute: 4,
    easierId: "plank",
    harderId: "hollow_hold",
  },
  {
    id: "bicycle_crunch",
    name: "Bicycle Crunch",
    pattern: "core_rotation",
    muscleGroups: ["core"],
    equipment: ["none"],
    tier: "building",
    impact: "low",
    cautionJoints: ["back"],
    cues: ["Elbow toward opposite knee.", "Move slow and controlled, not fast."],
    defaultSets: 3,
    defaultReps: 16,
    caloriesPerMinute: 5,
    easierId: "dead_bug",
    harderId: "mountain_climbers",
  },
  {
    id: "mountain_climbers",
    name: "Mountain Climbers",
    pattern: "core_rotation",
    muscleGroups: ["core", "cardio"],
    equipment: ["none"],
    tier: "progressing",
    impact: "moderate",
    cautionJoints: ["wrist", "shoulder"],
    cues: ["Plank position, drive knees to chest.", "Keep hips low and steady."],
    defaultSets: 3,
    defaultReps: 20,
    caloriesPerMinute: 8,
    easierId: "bicycle_crunch",
  },
  {
    id: "hollow_hold",
    name: "Hollow Body Hold",
    pattern: "core_stability",
    muscleGroups: ["core"],
    equipment: ["none"],
    tier: "advanced",
    impact: "low",
    cautionJoints: ["back"],
    cues: ["Lower back pressed to the floor.", "Arms and legs extended, ribs down."],
    defaultSets: 3,
    defaultReps: 20,
    isTimeBased: true,
    caloriesPerMinute: 5,
    easierId: "side_plank",
  },

  // ---- Cardio / conditioning ------------------------------------------------
  {
    id: "marching_in_place",
    name: "Marching in Place",
    pattern: "cardio",
    muscleGroups: ["cardio", "full_body"],
    equipment: ["none"],
    tier: "foundation",
    impact: "low",
    cautionJoints: [],
    cues: ["Lift knees to a comfortable height.", "Swing arms naturally."],
    defaultSets: 1,
    defaultReps: 60,
    isTimeBased: true,
    caloriesPerMinute: 4,
    harderId: "jumping_jacks",
  },
  {
    id: "jumping_jacks",
    name: "Jumping Jacks",
    pattern: "cardio",
    muscleGroups: ["cardio", "full_body"],
    equipment: ["none"],
    tier: "foundation",
    impact: "moderate",
    cautionJoints: ["knee", "ankle"],
    cues: ["Land softly on the balls of your feet.", "Full arm swing overhead."],
    defaultSets: 2,
    defaultReps: 30,
    isTimeBased: true,
    caloriesPerMinute: 8,
    easierId: "marching_in_place",
    harderId: "high_knees",
  },
  {
    id: "high_knees",
    name: "High Knees",
    pattern: "cardio",
    muscleGroups: ["cardio", "core"],
    equipment: ["none"],
    tier: "building",
    impact: "moderate",
    cautionJoints: ["knee"],
    cues: ["Drive knees up toward hip height.", "Stay light and quick on your feet."],
    defaultSets: 3,
    defaultReps: 30,
    isTimeBased: true,
    caloriesPerMinute: 9,
    easierId: "jumping_jacks",
    harderId: "step_ups",
  },
  {
    id: "step_ups",
    name: "Step-Ups",
    pattern: "cardio",
    muscleGroups: ["quads", "glutes", "cardio"],
    equipment: ["none", "bench"],
    tier: "building",
    impact: "moderate",
    cautionJoints: ["knee"],
    cues: ["Full foot on the step before pressing up.", "Control the step back down."],
    defaultSets: 3,
    defaultReps: 12,
    caloriesPerMinute: 7,
    easierId: "high_knees",
    harderId: "burpee",
  },
  {
    id: "burpee",
    name: "Burpee",
    pattern: "cardio",
    muscleGroups: ["full_body", "cardio"],
    equipment: ["none"],
    tier: "advanced",
    impact: "high",
    cautionJoints: ["knee", "wrist", "shoulder"],
    cues: ["Squat, kick back to a plank, jump feet in, stand and jump."],
    defaultSets: 4,
    defaultReps: 10,
    caloriesPerMinute: 12,
    easierId: "step_ups",
  },
];

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_LIBRARY.find((exercise) => exercise.id === id);
}

export function getExercisesByPattern(pattern: Exercise["pattern"]): Exercise[] {
  return EXERCISE_LIBRARY.filter((exercise) => exercise.pattern === pattern);
}
